version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "http://datingapp-s3-frontend.s3-website.us-east-2.amazonaws.com/"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build
artifacts:
    files:
        - '**/*'
    base-directory: 'dist/Angular8JwtAuth*'
    discard-paths: yes
